version: "3.7"

services:
  nodegoat_dev_web:
    build: .
    volumes:
      - ./contrast_security.yaml:/nodegoat/contrast_security.yaml
    environment:
      NODE_ENV:
      MONGODB_URI: mongodb://mongo:27017/nodegoat
    container_name: nodegoat-contrast
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && node ./node_modules/node_contrast server.js; do sleep 2; done"
    ports:
      - "4000:4000"

  mongo:
    image: mongo:latest
    user: mongodb
    expose:
      - 27017
