version: "3.7"

services:
  nodegoat_dev_web:
    image: smithst987/nodegoat:latest
    container_name: nodegoat    
    build: .
    volumes:
      - ./contrast_security.yaml:/app/nodegoat/contrast_security.yaml
    environment:
      NODE_ENV:
      MONGODB_URI: mongodb://mongo:27017/nodegoat
      - CONTRAST_CONFIG_PATH=/app/nodegoat/contrast_security.yaml   
      - CONTRAST__ENABLE=TRUE
      - CONTRAST__AGENT__NODE__REWRITE_CACHE__ENABLE=true
      - CONTRAST__AGENT__NODE__REWRITE_CACHE__PATH=.contrast
      - CONTRAST__APPLICATION__NAME=NodeGoat
      - CONTRAST__APPLICATION__GROUP=application_control_2
      - CONTRAST__APPLICATION__METADATA=bU=PS, contact=steve.smith@contrastsecurity.com
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"
    ports:
      - "4000:4000"

  mongo:
    image: mongo:latest
    user: mongodb
    expose:
      - 27017
